# name for workflow
name: WeatherApp

# event for the work (when work should start)
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

# define job to do
jobs:
  # build apk
  build:
    # OS where to perform the job
    runs-on: windows-latest

    # Steps to execute inside job
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.0

      # List files to ensure gradlew.bat is present
      - name: List files in directory
        run: dir

      # Set up Java JDK 17
      - name: Setup Java JDK
        uses: actions/setup-java@v4.4.0
        with:
          java-version: "17"
          distribution: "adopt"

      # Run Gradle build on Windows
      - name: Run Gradle build
        run: .\gradlew.bat build

      # Upload the APK as a build artifact
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3.2.1
        with:
          name: WeatherApp.apk
          path: app/build/outputs/apk/debug/app-debug.apk
